from pydantic import BaseModel, ConfigDict, field_validator
from datetime import date, datetime
from typing import Any, Optional, List, Dict
from pydantic import Field # Added for explicit field definition if needed
import ipaddress
from urllib.parse import urlparse


class UserBase(BaseModel):
    # Use a plain string here because the default admin uses a .local domain
    # which is not considered a valid RFC-compliant email by EmailStr.
    username: Optional[str] = Field(None, max_length=100)
    email: str

class UserCreate(UserBase):
    password: str

class UserRead(UserBase):
    id: int
    is_admin: bool

    model_config = ConfigDict(from_attributes=True)

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class TwoFactorChallenge(BaseModel):
    requires_2fa: bool = True
    two_factor_token: str
    message: str


class LoginResponse(BaseModel):
    is_first_login: Optional[bool] = None

class TokenData(BaseModel):
    email: Optional[str] = None


class BootstrapStatus(BaseModel):
    needs_admin: bool


class BootstrapAdminCreate(BaseModel):
    username: str
    password: str
    email: Optional[str] = None


class DetectionBase(BaseModel):
    technique_id: str = Field(..., max_length=50)
    title: str = Field(..., max_length=500)
    description: Optional[str] = Field(None, max_length=10000)
    sigma_rule: Optional[str] = Field(None, max_length=50000)
    siem_type: str = Field(..., max_length=50)
    siem_query: str = Field(..., max_length=10000)
    scheduled: Optional[bool] = False # for future

    # Fields for last test status and score
    last_result: Optional[str] = None
    last_score: Optional[int] = None
    last_tested_at: Optional[datetime] = None
    last_pass_at: Optional[datetime] = None
    last_fail_at: Optional[datetime] = None
    last_alert_at: Optional[datetime] = None
    status: Optional[str] = None
    last_reviewed_at: Optional[datetime] = None
    owner: Optional[str] = None
    notes: Optional[str] = None


class DetectionCreate(DetectionBase):
    # No id here, DB generates it
    pass


LIFECYCLE_STAGES = {
    "identify",
    "design",
    "develop",
    "test",
    "deploy",
    "maintain",
}


class DetectionUpdate(BaseModel):
    """Schema for partial detection updates (PATCH)."""
    owner: Optional[str] = Field(None, max_length=255, description="Email of the detection owner")
    notes: Optional[str] = Field(None, max_length=10000, description="Review notes")
    status: Optional[str] = Field(None, max_length=50, description="Lifecycle status")
    criticality: Optional[str] = Field(None, max_length=20, description="Criticality level")
    lifecycle_stage: Optional[str] = Field(
        None,
        max_length=20,
        description=(
            "Detection engineering lifecycle stage. One of: "
            "identify, design, develop, test, deploy, maintain."
        ),
    )

    @field_validator("lifecycle_stage")
    @classmethod
    def _validate_lifecycle_stage(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        normalized = v.strip().lower()
        if normalized not in LIFECYCLE_STAGES:
            raise ValueError(
                "lifecycle_stage must be one of: "
                + ", ".join(sorted(LIFECYCLE_STAGES))
            )
        return normalized


class Detection(DetectionBase):
    id: str
    criticality: Optional[str] = Field(
        None,
        max_length=20,
        description="Criticality level returned with detection records",
    )
    created_at: Optional[datetime] = None
    last_updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

class TestBase(BaseModel):
    # detection_id can be null for scenario / telemetry-only runs,
    # so keep this optional to match the database shape.
    detection_id: Optional[str] = Field(None, max_length=50)
    technique_id: str = Field(..., max_length=50)
    marker: Optional[str] = Field(None, max_length=100) # Marker can be generated by backend
    environment: str = Field("lab", max_length=20)  # "lab" | "prod"
    # Run intent persisted on the row. Mirrors TestRunCreate.mode and is used by
    # the runner to pick the validation strategy.
    mode: str = Field("DETECTION_VALIDATION", max_length=50)
    endpoint: Optional[str] = Field(None, max_length=255)
    atomic_test_id: Optional[str] = Field(None, max_length=255)
    atomic_test_name: Optional[str] = Field(None, max_length=500)
    atomic_test_number: Optional[int] = Field(None, ge=1, le=999)
    initiated_by_user_id: Optional[int] = None
    initiated_by_email: Optional[str] = Field(None, max_length=255)
    initiated_by_username: Optional[str] = Field(None, max_length=100)
    initiated_by_role: Optional[str] = Field(None, max_length=100)
    status: str = Field("pending", max_length=50)
    result: Optional[str] = Field(None, max_length=1000)
    score: Optional[int] = None
    # summary: Optional[str] = None # Removed as per new model
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    # Hash of the detection's rule-defining fields at the moment this Test
    # was created. NULL for tests created before versioning shipped, and for
    # scenario-driven runs that don't target a Detection.
    detection_version_hash: Optional[str] = Field(None, max_length=64)

class TestCreate(TestBase):
    pass

class Test(TestBase):
    id: int
    started_at: datetime # Re-added
    status: str # Re-added

    model_config = ConfigDict(from_attributes=True)


class DetectionVersionKPI(BaseModel):
    """Per-rule-version validation KPIs.

    A "version" is a unique value of ``Test.detection_version_hash``.
    ``version_label`` is assigned by the server as v1, v2, ... ordered by
    ``first_seen`` ASC. ``is_current`` flags the bucket whose hash matches
    the live detection's rule fields.

    ``delta_pass_pct`` is the answer to "did my last edit hurt?" — a signed
    integer percentage point delta between this version's pass rate and
    the previous version's pass rate. NULL on v1 (no predecessor) and on
    any version comparing against a zero-run predecessor. ``compared_to_label``
    names the version we compared against, so the UI can render
    "▼ 25 pts vs v2" without inventing the relationship client-side.
    """

    version_label: str
    version_hash: Optional[str] = None
    runs: int
    pass_rate: float
    fail_rate: float
    inconclusive_rate: float
    first_seen: Optional[datetime] = None
    last_seen: Optional[datetime] = None
    is_current: bool
    delta_pass_pct: Optional[int] = None
    compared_to_label: Optional[str] = None


class DetectionVersionKPIResponse(BaseModel):
    """Response shape for the per-detection version KPI endpoint.

    ``versions`` only contains the linear sequence (v1 → v2 → … →
    current). The pre-versioning ``Legacy`` bucket — runs whose rule
    state is not knowable — lives in its own ``legacy`` field. Splitting
    keeps the UI simple: the main list is comparable, ordered, and
    delta-able; legacy is a footnote you can collapse or hide.
    """

    detection_id: str
    current_version_hash: str
    versions: list[DetectionVersionKPI]
    legacy: Optional[DetectionVersionKPI] = None


# Valid run modes. Kept as a constant so the router, scheduler, and runner
# can share a single source of truth without circular imports.
TEST_RUN_MODES = ("DETECTION_VALIDATION", "ALERT_CHECK", "TELEMETRY_CHECK")


class TestRunCreate(BaseModel):
    # Optional detection that this run is tied to. When omitted, the test is
    # treated as a scenario/telemetry run driven by technique_id only.
    detection_id: Optional[str] = None
    # Optional technique identifier for scenario‑driven runs (e.g. from Explore).
    technique_id: Optional[str] = None
    environment: str = "lab"
    endpoint: Optional[str] = None
    atomic_test_id: Optional[str] = Field(None, max_length=255)
    atomic_test_name: Optional[str] = Field(None, max_length=500)
    atomic_test_number: Optional[int] = Field(None, ge=1, le=999)
    # Hint from the UI about how this run should be interpreted. The runner
    # branches on this value to choose between detection-rule scoring and
    # telemetry-only scoring.
    mode: Optional[str] = "DETECTION_VALIDATION"

    @field_validator("mode")
    @classmethod
    def _validate_mode(cls, value: Optional[str]) -> str:
        normalized = (value or "DETECTION_VALIDATION").upper()
        if normalized not in TEST_RUN_MODES:
            raise ValueError(
                f"mode must be one of {TEST_RUN_MODES}, got {value!r}"
            )
        return normalized

# Removed TestRunRequest as it is replaced by TestRunCreate

class TestArtifactBase(BaseModel):
    test_id: int # Re-added
    atomic_command: Optional[str] = None
    siem_sample_events: Optional[str] = None
    # event_count: Optional[int] = None # Removed as per new model
    ai_explanation: Optional[str] = None
    ai_suggested_rule: Optional[str] = None
    ai_root_cause_category: Optional[str] = "OTHER"
    ai_confidence_score: Optional[int] = 0

class TestArtifactCreate(TestArtifactBase):
    pass

class TestArtifact(TestArtifactBase):
    id: int

    model_config = ConfigDict(from_attributes=True)


class TestWithDetectionTitle(Test):
    detection_title: str
    atomic_command: Optional[str] = None

class TestDetailResponse(Test):
    detection: Optional[Detection] = None
    artifact: Optional[TestArtifact] = None # No longer a forward reference


class DetectionSignalPayload(BaseModel):
    """Payload shape for a single qualifying detection/alert used in scoring."""

    detection_time: datetime
    is_qualifying: bool = True

    specificity_level: Optional[str] = None
    detection_type: Optional[str] = None
    uses_process_tree: bool = False
    uses_multi_condition: bool = False
    expected_fp_rate: Optional[str] = None
    severity: Optional[str] = None

    # 5W enrichment fields
    user_name: Optional[str] = None
    user_domain: Optional[str] = None
    user_email: Optional[str] = None
    user_id: Optional[str] = None
    user_sid: Optional[str] = None

    host_name: Optional[str] = None
    host_fqdn: Optional[str] = None
    asset_id: Optional[str] = None
    device_id: Optional[str] = None
    asset_criticality: Optional[str] = None
    os_type: Optional[str] = None
    os_version: Optional[str] = None

    process_name: Optional[str] = None
    process_command_line: Optional[str] = None
    parent_process_name: Optional[str] = None
    parent_process_id: Optional[str] = None
    event_type: Optional[str] = None

    event_time: Optional[datetime] = None
    log_time: Optional[datetime] = None

    src_ip: Optional[str] = None
    src_port: Optional[int] = None
    src_geo: Optional[str] = None
    src_hostname: Optional[str] = None
    src_asn: Optional[str] = None

    dest_ip: Optional[str] = None
    dest_domain: Optional[str] = None
    dest_port: Optional[int] = None
    dest_hostname: Optional[str] = None
    dest_geo: Optional[str] = None
    url: Optional[str] = None

    technique_id: Optional[str] = None
    tactic: Optional[str] = None
    framework: Optional[str] = None
    rule_name: Optional[str] = None
    detection_rule_id: Optional[str] = None
    category: Optional[str] = None

    log_source: Optional[str] = None
    vendor: Optional[str] = None
    env_size_bucket: Optional[str] = None


class ScoreTestRunRequest(BaseModel):
    """Request body for computing a C/T/F/E + 5W score for a test run."""

    attack_start_time: datetime
    detections: List[DetectionSignalPayload]


class ScoreTestRunResponse(BaseModel):
    coverage: int
    timeliness: int
    fidelity: float
    enrichment: int
    enrichment_breakdown: Dict[str, int]
    base_score: float
    ml_adjustment: float
    final_score: float
    delay_seconds: Optional[float]


class AtomicArgSpec(BaseModel):
    name: str
    label: str
    type: Optional[str] = "string"
    required: Optional[bool] = True
    default: Optional[str] = None
    description: Optional[str] = None
    options: Optional[List[str]] = None


class AtomicTestDefinition(BaseModel):
    id: str
    technique_id: str
    test_number: Optional[int] = None
    name: str
    description: Optional[str] = None
    source: str = "atomic-red-team"
    platforms: List[str] = []
    is_safe: Optional[bool] = True
    args: List[AtomicArgSpec] = []
    executor_name: Optional[str] = None
    command: Optional[str] = None
    cleanup_command: Optional[str] = None


class MitreTechnique(BaseModel):
    id: str
    name: str
    tactics: List[str]  # Human-readable tactic names, e.g. "Execution"
    is_subtechnique: bool = False
    # ATT&CK-standard `x_mitre_platforms` and `x_mitre_data_sources`. Populated
    # from the enterprise-attack.json catalog when available; empty lists for
    # the built-in sample. The frontend uses `platforms` for the OS filter
    # and `data_sources` to show "to detect this, you need…".
    platforms: List[str] = []
    data_sources: List[str] = []


# --- Coverage summary / trend (MITRE heatmap navigator) --------------------


class CoverageTotals(BaseModel):
    total_techniques: int
    validated: int
    at_risk: int
    mapped: int
    unmapped: int


class CoverageTechniqueGap(BaseModel):
    technique_id: str
    technique_name: str
    tactics: List[str] = []
    detection_count: int
    max_criticality: str  # LOW | MEDIUM | HIGH | CRITICAL
    last_score: Optional[float] = None
    last_result: Optional[str] = None


class CoverageSummary(BaseModel):
    totals: CoverageTotals
    # Simple coverage ignores criticality — (validated techniques) / (total techniques).
    simple_coverage_percent: float
    # Weighted coverage weighs each mapped technique by the max criticality of
    # its detections, so "validated PowerShell" counts more than "validated
    # T1595 active scanning". Denominator is mapped-technique weight, i.e. a
    # "how much of what you've instrumented is actually working" metric.
    weighted_coverage_percent: float
    top_untested_high_value: List[CoverageTechniqueGap] = []
    top_failing_high_value: List[CoverageTechniqueGap] = []
    captured_at: datetime


class CoverageTrendPoint(BaseModel):
    day: date  # ISO-8601 YYYY-MM-DD
    validated: int
    tested: int


class CoverageTrend(BaseModel):
    days: int
    points: List[CoverageTrendPoint]

class DetectionAlert(BaseModel):
    id: int
    name: str
    time: datetime
    severity: str
    host: Optional[str] = None
    query: str
    raw_event: str
    # Optional link back to the PurveX test this alert was associated with,
    # when it was generated by a validation run rather than a live incident.
    test_id: Optional[int] = None


class ReportBase(BaseModel):
    start_date: datetime
    end_date: datetime
    environments: List[str]  # ["lab", "dev", "prod"]


class ReportCreate(ReportBase):
    title: Optional[str] = None


class Report(ReportBase):
    id: int
    report_id: str
    organization_id: int
    generated_by: int
    generated_at: datetime
    title: str
    overall_health_score: Optional[int] = None
    total_detections: int
    total_tests: int
    file_path: Optional[str] = None
    file_size: Optional[int] = None

    model_config = ConfigDict(from_attributes=True)


class OrganizationBase(BaseModel):
    name: str
    primary_contact_email: Optional[str] = None
    timezone: str = "UTC"
    locale: str = "en_US"
    default_environment_names: str = '["lab", "dev", "prod"]'
    compliance_mode_flags: str = '[]'

class OrganizationCreate(OrganizationBase):
    pass

class Organization(OrganizationBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class SIEMConnectionBase(BaseModel):
    siem_type: str
    name: str
    url: str
    auth_type: str
    credentials: Optional[str] = None
    last_validated_at: Optional[datetime] = None
    default_windows_index: Optional[str] = None
    default_linux_index: Optional[str] = None
    default_cloud_index: Optional[str] = None
    log_marker_pattern: str = "purvex_*"

class SIEMConnectionCreate(SIEMConnectionBase):
    @field_validator("url")
    @classmethod
    def _validate_siem_url(cls, value: str) -> str:
        normalized = (value or "").strip()
        parsed = urlparse(normalized)
        if parsed.scheme not in {"http", "https"}:
            raise ValueError("SIEM URL must start with http:// or https://")
        if not parsed.hostname:
            raise ValueError("SIEM URL must include a hostname")
        if parsed.username or parsed.password:
            raise ValueError("SIEM URL must not embed credentials")
        if parsed.query or parsed.fragment:
            raise ValueError("SIEM URL must not include query parameters or fragments")

        host = parsed.hostname.lower()
        if host in {"localhost", "0.0.0.0"}:
            raise ValueError("SIEM URL must not point to a loopback host")

        metadata_hosts = {
            "metadata.google.internal",
            "metadata",
            "metadata.azure.internal",
            "169.254.169.254",
        }
        if host in metadata_hosts:
            raise ValueError("SIEM URL must not point to a cloud metadata endpoint")

        try:
            ip = ipaddress.ip_address(host)
        except ValueError:
            ip = None

        if ip is not None:
            if ip.is_loopback or ip.is_unspecified:
                raise ValueError("SIEM URL must not point to a loopback host")
            if ip.is_link_local:
                raise ValueError("SIEM URL must not point to a link-local address")
            if ip.is_reserved or ip.is_multicast:
                raise ValueError("SIEM URL must not point to a reserved address")

        return normalized.rstrip("/")

class SIEMConnection(SIEMConnectionBase):
    id: int
    organization_id: Optional[int] = None
    status: Optional[str] = None
    credentials_present: bool = False

    model_config = ConfigDict(from_attributes=True)

class SIEMAlert(BaseModel):
    alert_id: Optional[str] = None
    rule_id: Optional[str] = None
    rule_name: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    fired_at: Optional[datetime] = None
    last_seen_at: Optional[datetime] = None
    source: Optional[str] = None
    raw_event: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMEvent(BaseModel):
    event_id: Optional[str] = None
    event_time: Optional[datetime] = None
    severity: Optional[str] = None
    source: Optional[str] = None
    host: Optional[str] = None
    user: Optional[str] = None
    action: Optional[str] = None
    raw_event: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMEvidence(BaseModel):
    event_time: Optional[datetime] = None
    severity: Optional[str] = None
    host: Optional[str] = None
    user: Optional[str] = None
    dest: Optional[str] = None
    src: Optional[str] = None
    signature: Optional[str] = None
    sourcetype: Optional[str] = None
    index: Optional[str] = None

class SIEMEvidenceBundle(BaseModel):
    count: int
    items: List[SIEMEvidence]
    deep_link: Optional[str] = None

class SIEMRule(BaseModel):
    rule_id: Optional[str] = None
    name: Optional[str] = None
    enabled: Optional[bool] = None
    severity: Optional[str] = None
    schedule: Optional[str] = None
    last_run_at: Optional[datetime] = None
    query: Optional[str] = None
    evidence_url: Optional[str] = None

class SIEMHealth(BaseModel):
    status: str
    auth_status: Optional[str] = None
    ingestion_lag_seconds: Optional[int] = None
    last_event_at: Optional[datetime] = None
    last_alert_at: Optional[datetime] = None
    message: Optional[str] = None

class EnvironmentRunnerConfigBase(BaseModel):
    organization_id: Optional[int] = None
    environment_name: str
    runner_type: str = "SSH"
    hostname: Optional[str] = None
    port: int = 22
    username: Optional[str] = None
    auth_method: str = "key"
    key_path: Optional[str] = None
    ssh_host_key_sha256: Optional[str] = None
    allowed_test_types: str = '["Atomic only"]'
    max_concurrent_tests: int = 1
    heartbeat_interval_seconds: int = 5
    alert_offline_minutes: int = 5
    os: Optional[str] = None
    ip_address: Optional[str] = None
    agent_version: Optional[str] = None
    last_check_in: Optional[datetime] = None
    status: Optional[str] = None
    owner_name: Optional[str] = None
    owner_email: Optional[str] = None
    runner_token_last_rotated_at: Optional[datetime] = None
    runner_token_expires_at: Optional[datetime] = None

class EnvironmentRunnerHeartbeat(BaseModel):
    os: Optional[str] = None
    ip_address: Optional[str] = None
    agent_version: Optional[str] = None
    status: Optional[str] = None

class EnvironmentRunnerConfigCreate(EnvironmentRunnerConfigBase):
    pass

class EnvironmentRunnerConfig(EnvironmentRunnerConfigBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class EnvironmentRunnerRegistrationResponse(EnvironmentRunnerConfig):
    runner_token: Optional[str] = None

class AgentCommand(BaseModel):
    id: int
    runner_id: int
    command_type: str
    status: str
    payload: Optional[str] = None
    message: Optional[str] = None
    created_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)

class AgentCommandAck(BaseModel):
    status: str
    message: Optional[str] = None

class TestingPolicyBase(BaseModel):
    organization_id: Optional[int] = None
    allowed_environments: str = '["lab", "dev"]'
    default_marker_prefix: str = "purvex_"
    include_env_timestamp_in_marker: bool = True
    tag_test_alerts: str = "Purvex_Test = true"
    notify_before_prod_tests: bool = False
    disallow_tests_during_business_hours: bool = False
    business_hours_start: str = "09:00"
    business_hours_end: str = "17:00"
    only_prod_during_maintenance_windows: bool = False
    # SIEM-style data retention for test runs and stored SIEM samples (in days).
    test_data_retention_days: int = 90
    retention_pass_days_lab: int = 7
    retention_fail_days_lab: int = 30
    retention_pass_days_dev: int = 30
    retention_fail_days_dev: int = 90
    retention_pass_days_prod: int = 90
    retention_fail_days_prod: int = 180

class TestingPolicyCreate(TestingPolicyBase):
    pass

class TestingPolicy(TestingPolicyBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class DetectionScoringBase(BaseModel):
    organization_id: Optional[int] = None
    base_scoring_explanation: str = "PASS with logs → base 80, FAIL with logs → base 30, INCONCLUSIVE → base 50"
    pass_log_base_score: int = 80
    fail_log_base_score: int = 30
    inconclusive_base_score: int = 50
    recent_pass_fail_weight: int = 10
    false_positive_penalty: int = 10
    environment_penalty_discount: int = 0
    health_threshold_healthy: int = 80
    health_threshold_at_risk: int = 50
    health_threshold_critical: int = 20
    scoring_window_n_tests: int = 10

class DetectionScoringCreate(DetectionScoringBase):
    pass

class DetectionScoring(DetectionScoringBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class AIAssistantSettingsBase(BaseModel):
    organization_id: Optional[int] = None
    provider: str = "OpenAI"
    model_name: str = "gpt-4o-mini"
    api_base_url: str = "https://api.openai.com/v1"
    analysis_mode: Optional[str] = "fast"
    generate_tuning_suggestions: bool = True
    explain_test_failures: bool = True
    automatically_modify_rules: bool = False
    strip_ips_hostnames: bool = True
    no_raw_logs_outside_env: bool = False
    audience_preference: str = "Analyst"

    model_config = ConfigDict(protected_namespaces=())

class AIAssistantSettingsCreate(AIAssistantSettingsBase):
    api_key: Optional[str] = None

class AIAssistantSettings(AIAssistantSettingsBase):
    id: int

    model_config = ConfigDict(from_attributes=True)


class AuditEvent(BaseModel):
    id: int
    user_id: Optional[int] = None
    user_email: Optional[str] = None
    action: str
    resource_type: Optional[str] = None
    resource_id: Optional[str] = None
    details: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SandboxEnvironmentBase(BaseModel):
    organization_id: Optional[int] = None
    external_id: Optional[str] = None
    display_name: str = "PurveX Lab"
    status: str = "provisioning"
    size: Optional[str] = "small"
    provider: Optional[str] = "purvex_cloud"
    extra_metadata: Optional[str] = None


class SandboxEnvironmentCreate(SandboxEnvironmentBase):
    pass


class SandboxEnvironment(SandboxEnvironmentBase):
    id: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class TestScheduleBase(BaseModel):
    detection_id: Optional[str] = None
    technique_id: Optional[str] = None
    environment: str = "lab"
    mode: str = "DETECTION_VALIDATION"
    schedule_type: str  # "once" | "interval" | "cron"
    run_at: Optional[datetime] = None
    interval_seconds: Optional[int] = None
    cron_expression: Optional[str] = None
    enabled: bool = True

    @field_validator("mode")
    @classmethod
    def _validate_mode(cls, value: Optional[str]) -> str:
        normalized = (value or "DETECTION_VALIDATION").upper()
        if normalized not in TEST_RUN_MODES:
            raise ValueError(
                f"mode must be one of {TEST_RUN_MODES}, got {value!r}"
            )
        return normalized


class TestScheduleCreate(TestScheduleBase):
    pass


class TestScheduleUpdate(BaseModel):
    enabled: Optional[bool] = None
    run_at: Optional[datetime] = None
    interval_seconds: Optional[int] = None
    cron_expression: Optional[str] = None


class TestSchedule(TestScheduleBase):
    id: int
    organization_id: Optional[int] = None
    created_by_user_id: Optional[int] = None
    created_at: datetime
    last_run_at: Optional[datetime] = None
    next_run_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


# ---------------------------------------------------------------------------
# Detection proposals (Sprint 2 — AI remediation guardrails)
# ---------------------------------------------------------------------------

# Whitelist of Detection fields an AI/user can propose changes to. Deliberately
# narrow: status/lifecycle bookkeeping columns (last_*, created_at) are not
# editable through proposals — they're system-owned. ``criticality`` is
# included so analysts can propose a severity re-tier with justification,
# but RBAC still gates approval via DETECTIONS_CRITICALITY_UPDATE.
PROPOSAL_EDITABLE_FIELDS = {
    "title",
    "description",
    "sigma_rule",
    "siem_type",
    "siem_query",
    "technique_id",
    "status",
    "criticality",
    "owner",
    "notes",
    "lifecycle_stage",
}

PROPOSAL_ACTIONS = {"create", "update", "delete"}
PROPOSAL_PROPOSER_KINDS = {"ai", "user", "git"}
PROPOSAL_STATUSES = {"pending", "approved", "rejected", "applied", "superseded"}


class DetectionProposalCreate(BaseModel):
    """Body for ``POST /proposals``.

    ``target_fields`` is the partial patch the proposer wants to apply.
    For ``action=="update"`` it must be non-empty and keyed by a subset
    of :data:`PROPOSAL_EDITABLE_FIELDS`. For ``action=="delete"`` it is
    ignored. For ``action=="create"`` it must contain the full set of
    non-nullable Detection fields — validated in the router, not here,
    so schema errors and tenant errors return different status codes.
    """

    detection_id: Optional[str] = None
    action: str = "update"
    proposed_by_kind: str = "ai"
    proposed_by_label: str = Field("AI Assistant", max_length=200)
    reason: Optional[str] = Field(None, max_length=4000)
    target_fields: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("action")
    @classmethod
    def _validate_action(cls, v: str) -> str:
        if v not in PROPOSAL_ACTIONS:
            raise ValueError(f"action must be one of {sorted(PROPOSAL_ACTIONS)}")
        return v

    @field_validator("proposed_by_kind")
    @classmethod
    def _validate_kind(cls, v: str) -> str:
        if v not in PROPOSAL_PROPOSER_KINDS:
            raise ValueError(
                f"proposed_by_kind must be one of {sorted(PROPOSAL_PROPOSER_KINDS)}"
            )
        return v

    @field_validator("target_fields")
    @classmethod
    def _validate_fields(cls, v: Dict[str, Any]) -> Dict[str, Any]:
        invalid = [k for k in v if k not in PROPOSAL_EDITABLE_FIELDS]
        if invalid:
            raise ValueError(
                f"fields not allowed in proposals: {sorted(invalid)}"
            )
        return v


class DetectionProposalReview(BaseModel):
    """Body for approve/reject — a reviewer note is optional but encouraged
    for rejects so the proposer (especially an AI) has signal to learn from."""

    note: Optional[str] = Field(None, max_length=4000)


class DetectionProposalDiffEntry(BaseModel):
    """A single field-level change, used by the frontend diff viewer."""

    field: str
    before: Any = None
    after: Any = None
    changed: bool = True


class DetectionProposalOut(BaseModel):
    """Proposal response payload with computed diff.

    ``diff`` is derived server-side from ``target_fields`` vs
    ``current_snapshot``. We compute it at read time (not write time)
    so a fresh diff is always rendered against the current target —
    and drift is obvious from ``stale=True``.
    """

    id: str
    organization_id: int
    detection_id: Optional[str] = None
    detection_title: Optional[str] = None
    proposed_by_kind: str
    proposed_by_user_id: Optional[int] = None
    proposed_by_label: str
    action: str
    status: str
    reason: Optional[str] = None
    target_fields: Dict[str, Any] = Field(default_factory=dict)
    current_snapshot: Optional[Dict[str, Any]] = None
    diff: List[DetectionProposalDiffEntry] = Field(default_factory=list)
    stale: bool = False
    created_at: datetime
    reviewed_at: Optional[datetime] = None
    reviewed_by_user_id: Optional[int] = None
    reviewed_by_label: Optional[str] = None
    review_note: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


class DetectionProposalStats(BaseModel):
    """Sidebar badge payload — cheap counts by status."""

    pending: int = 0
    approved: int = 0
    applied: int = 0
    rejected: int = 0
    superseded: int = 0


# ---------------------------------------------------------------------------
# Detection sources (Sprint 3 — Detection-as-Code)
# ---------------------------------------------------------------------------

DETECTION_SOURCE_AUTH_TYPES = {"none", "token"}
DETECTION_SOURCE_PROVIDERS = {"git"}


class DetectionSourceBase(BaseModel):
    """Shared fields between create / update / read payloads.

    ``path_glob`` is a git-style double-star glob, evaluated client-side
    (in the sync service) rather than by the server shell, so we don't
    need to shell-escape user input. ``auth_secret`` is plaintext on the
    wire and encrypted at rest.
    """

    name: str = Field(..., min_length=1, max_length=200)
    repo_url: str = Field(..., min_length=1, max_length=1000)
    branch: str = Field("main", max_length=200)
    path_glob: str = Field("detections/**/*.yml", max_length=500)
    auth_type: str = Field("none", max_length=20)
    enabled: bool = True

    @field_validator("repo_url")
    @classmethod
    def _validate_repo_url(cls, v: str) -> str:
        # Lock to http(s) URLs. SSH (``git@…``) is deliberately deferred
        # so we don't need to manage deploy keys in V1.
        lower = v.lower()
        if not (lower.startswith("http://") or lower.startswith("https://")):
            raise ValueError("repo_url must be an http(s) URL")
        return v

    @field_validator("auth_type")
    @classmethod
    def _validate_auth_type(cls, v: str) -> str:
        if v not in DETECTION_SOURCE_AUTH_TYPES:
            raise ValueError(
                f"auth_type must be one of {sorted(DETECTION_SOURCE_AUTH_TYPES)}"
            )
        return v


class DetectionSourceCreate(DetectionSourceBase):
    provider: str = "git"
    # Plaintext. Encrypted server-side before storage. Omit entirely for
    # public repos with ``auth_type="none"``.
    auth_secret: Optional[str] = Field(None, max_length=4000)

    @field_validator("provider")
    @classmethod
    def _validate_provider(cls, v: str) -> str:
        if v not in DETECTION_SOURCE_PROVIDERS:
            raise ValueError(
                f"provider must be one of {sorted(DETECTION_SOURCE_PROVIDERS)}"
            )
        return v


class DetectionSourceUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=200)
    repo_url: Optional[str] = Field(None, min_length=1, max_length=1000)
    branch: Optional[str] = Field(None, max_length=200)
    path_glob: Optional[str] = Field(None, max_length=500)
    auth_type: Optional[str] = Field(None, max_length=20)
    # Use ``auth_secret=""`` (empty string) to clear the stored token.
    # Omit to leave it unchanged.
    auth_secret: Optional[str] = Field(None, max_length=4000)
    enabled: Optional[bool] = None


class DetectionSource(DetectionSourceBase):
    id: int
    organization_id: int
    provider: str
    # Never returned — avoids accidentally leaking the token through the API.
    has_auth_secret: bool = False

    last_synced_at: Optional[datetime] = None
    last_sync_status: Optional[str] = None
    last_sync_error: Optional[str] = None
    last_commit_sha: Optional[str] = None
    last_created_count: int = 0
    last_updated_count: int = 0
    last_proposals_count: int = 0
    last_skipped_count: int = 0

    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DetectionSourceSyncResult(BaseModel):
    """Outcome of a single ``POST /detection-sources/{id}/sync`` run."""

    source_id: int
    commit_sha: Optional[str] = None
    created: int = 0
    updated: int = 0
    proposals: int = 0
    skipped: int = 0
    errors: List[str] = Field(default_factory=list)


class DetectionExport(BaseModel):
    """YAML payload for ``GET /detections/{id}/export`` convenience endpoint."""

    id: str
    yaml: str


# ---------------------------------------------------------------------------
# Detection git audit mirror (Sprint 4 — SIEM → Git one-way write-back)
# ---------------------------------------------------------------------------
DETECTION_MIRROR_WRITE_MODES = {"direct", "branch", "pr"}
DETECTION_MIRROR_AUTH_TYPES = {"none", "token"}


class DetectionGitMirrorBase(BaseModel):
    """Shared fields between create / update / read payloads.

    ``path_template`` supports ``{siem}``, ``{technique_id}``,
    ``{external_id}``, ``{slug}`` tokens — all slugified before
    interpolation so a malformed SIEM rule id can't break the glob.
    """

    name: str = Field(..., min_length=1, max_length=200)
    repo_url: str = Field(..., min_length=1, max_length=1000)
    branch: str = Field("main", max_length=200)
    path_template: str = Field(
        "detections/{siem}/{technique_id}/{slug}.yml", max_length=500
    )
    commit_author_name: str = Field("PurveX Bot", max_length=200)
    commit_author_email: str = Field(
        "purvex-bot@purvex.local", max_length=320
    )
    write_mode: str = Field("direct", max_length=20)
    auth_type: str = Field("none", max_length=20)
    enabled: bool = True

    @field_validator("repo_url")
    @classmethod
    def _validate_repo_url(cls, v: str) -> str:
        lower = v.lower()
        if not (lower.startswith("http://") or lower.startswith("https://")):
            raise ValueError("repo_url must be an http(s) URL")
        return v

    @field_validator("write_mode")
    @classmethod
    def _validate_write_mode(cls, v: str) -> str:
        if v not in DETECTION_MIRROR_WRITE_MODES:
            raise ValueError(
                f"write_mode must be one of {sorted(DETECTION_MIRROR_WRITE_MODES)}"
            )
        return v

    @field_validator("auth_type")
    @classmethod
    def _validate_auth_type(cls, v: str) -> str:
        if v not in DETECTION_MIRROR_AUTH_TYPES:
            raise ValueError(
                f"auth_type must be one of {sorted(DETECTION_MIRROR_AUTH_TYPES)}"
            )
        return v


class DetectionGitMirrorCreate(DetectionGitMirrorBase):
    auth_secret: Optional[str] = Field(None, max_length=4000)


class DetectionGitMirrorUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=200)
    repo_url: Optional[str] = Field(None, min_length=1, max_length=1000)
    branch: Optional[str] = Field(None, max_length=200)
    path_template: Optional[str] = Field(None, max_length=500)
    commit_author_name: Optional[str] = Field(None, max_length=200)
    commit_author_email: Optional[str] = Field(None, max_length=320)
    write_mode: Optional[str] = Field(None, max_length=20)
    auth_type: Optional[str] = Field(None, max_length=20)
    # ``auth_secret=""`` clears the stored token; omit to leave unchanged.
    auth_secret: Optional[str] = Field(None, max_length=4000)
    enabled: Optional[bool] = None


class DetectionGitMirror(DetectionGitMirrorBase):
    id: int
    organization_id: int
    has_auth_secret: bool = False

    last_mirrored_at: Optional[datetime] = None
    last_mirror_status: Optional[str] = None
    last_mirror_error: Optional[str] = None
    last_commit_sha: Optional[str] = None
    last_commits_count: int = 0
    last_files_written: int = 0

    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DetectionMirrorPublishResult(BaseModel):
    """Outcome of a mirror publish run (bootstrap or delta)."""

    mirror_id: int
    commit_sha: Optional[str] = None
    files_written: int = 0
    commits: int = 0
    skipped: int = 0
    errors: List[str] = Field(default_factory=list)


class SIEMMirrorLinkUpdate(BaseModel):
    """Attach / detach a mirror to a SIEM connection."""

    audit_mirror_id: Optional[int] = None
    audit_mirror_enabled: bool = False
